### ISSUE TITLE
No content visible with 3 columns option

### ISSUE THREAD

**Issue by NZCyrus** [Jimmi08/RideBlue2#6]
![3column-rideblue2](https://user-images.githubusercontent.com/7886491/31602108-74abd13c-b2b8-11e7-8ed8-e33408637313.png)

No content is visible when 3 column option is selected from site theme. This applies to all content, ie. news, contact, plugins like links, and pages.

In my case, news is set as the home page for front page settings. My theme is currently up to date and I run on the latest commit of 2.1.7 (git)

**Comment by Jimmi08** [comment]
Thank you for posting this.

**Comment by Jimmi08** [comment]
Hi, I just installed version from e107.org (find themes, install content demo) and everything looks correct. Latest 2.1.7 github version.
 
![image](https://user-images.githubusercontent.com/5429548/31875059-b54faf1a-b7cc-11e7-8558-b91501192d23.png)
 
 
![image](https://user-images.githubusercontent.com/5429548/31875120-06fd1bc2-b7cd-11e7-8e4d-ce10ad25f23a.png)

![image](https://user-images.githubusercontent.com/5429548/31875124-0a6376f8-b7cd-11e7-90fa-eb66c6b68b13.png)

**Comment by NZCyrus** [comment]
Thank you for looking into this.

The issue seems to have been on my end. I noticed from 'Menu Manager' that the 3rd column had a number of active menus that I deactivated. After that I activated a few again, and all 3 columns showed up as it should. I'm not sure which menu item was the troublesome one, but everything is OK now.

Much appreciated :)

**Comment by Jimmi08** [comment]
You are welcome.
